### PR TITLE
fix: handle error happened in uploading new problem testdata

### LINKED ISSUE #179: Redirect to problem edit page after creating new problem but failing to upload the testcase
Currently, it takes two API requests to create a new problem
1. `POST /problem/manage` to create a new problem body with info like title, and get a pid number.
2. `PUT /problem/manage/<pid>` to upload the testcase.zip to the corresponding problem with pid.

If both requests complete successfully, the UI will bring users to that problem page.

The problem is that if step 2. failed, the UI will keep all values in the form and in the same page.

When users see the error messages and submit again, a new problem with same body will create, and that's not the user want in this user journey.

Expect to redirect to the problem edit page with that pid if only step 1. succeed and step 2. failed.

### PR DESCRIPTION
**Pull request by uier**
show a specific alert to provide info about the testdata failed to user, and then redirect to problem edit page to avoid re-creating new problems in the same page

For details, please see #179

Fix #179

Please see the video:
https://github.com/user-attachments/assets/a86c698a-49df-4db7-84b3-a789673606dd

### CODE REVIEW

File: src/pages/course/[name]/problem/new.vue [hunk 1]
```diff
@@ -63,10 +63,15 @@ async function submit() {
...
-    // TODO: additional handling if testcase upload fail
     const testdataForm = new FormData();
     testdataForm.append("case", testdata.value);
-    await api.Problem.modifyTestdata(problemId, testdataForm);
+    try {
+      await api.Problem.modifyTestdata(problemId, testdataForm);
+    } catch (error) {
+      alert("Problem created, but testdata upload failed.");
+      router.push(`/course/${route.params.name}/problem/${problemId}/edit`);
+      throw error;
```
Comment (Bogay) [inline src/pages/course/[name]/problem/new.vue:73]: Perhaps outside the scope of this issue. Could we add more detail to the UI about the error being responded to? What information needs to be displayed?

**Review by Bogay — APPROVED** [review]

File: src/pages/course/[name]/problem/new.vue (hunk 1 above)
Comment (uier) [reply src/pages/course/[name]/problem/new.vue:73]: Make sense, let me fix this

Comment (uier) [reply src/pages/course/[name]/problem/new.vue]: fixed, take a look

**Review by Bogay — APPROVED** [review]
