### PR TITLE
fix(PaginationButtons): make props reactive, otherwise when buttons r…

### LINKED ISSUE #15: PaginationButtons doesn't work properly

### PR DESCRIPTION
**Pull request by uier**
…endered before problemlist fetched, it would be incorrect

Closes #15

### CODE REVIEW

File: src/pages/course/[name]/submissions.vue [hunk 1]
```diff
@@ -35,13 +35,20 @@ const routeQuery = computed(() => ({
 const page = ref(routeQuery.value.page);
 const filter = ref<UserDefinedSubmissionQuery>({ ...routeQuery.value.filter });
 watchEffect(() => {
-  const query: any = { page: page.value };
+  // effect function runs after page changed or filter changed
+  // TODO: type query
```
Comment (Bogay) [inline src/pages/course/[name]/submissions.vue:39]: 或許可以把 issue 開起來？

**Review by Bogay — CHANGES_REQUESTED** [review]

**Review by Bogay — APPROVED** [review]
